pipeline:
  name: pl_automated_monitoring_CTRL_1077125
  use_test_data_on_nonprod: false
  dq_strict_mode: false

stages:
  extract:
    thresholds_raw:
      connector: snowflake
      options:
        sql: "@text:sql/monitoring_thresholds.sql"
  
  transform:
    monitoring_metrics:
      - function: custom/calculate_ctrl1077125_metrics
        options:
          thresholds_raw: $thresholds_raw
  
  ingress_validation:
    thresholds_raw:
      - type: count_check
        fatal: true
        envs:
          - qa
          - prod
        options:
          data_location: Snowflake
          threshold: 1
          table_name: ETIP_DB.PHDP_ETIP_CONTROLS_MONITORING.ETIP_CONTROLS_MONITORING_METRICS_DETAILS
    
    monitoring_metrics:
      - type: count_check
        fatal: true
        envs:
          - qa
          - prod
        options:
          data_location: API
          threshold: 1
          table_name: KMS_KEY_ORIGIN
  
  load:
    monitoring_metrics:
      - connector: onestream
        options:
          table_name: etip_controls_monitoring_metrics
          business_application: BAENTERPRISETECHINSIGHTS
          file_type: AVRO
          avro_schema: "@json:avro_schema.json"

  prepare_test_data:
    thresholds_raw:
      - function: head
        options:
          n: 500000

  export_test_data:
    thresholds_raw: