-- sqlfluff:dialect:snowflake
-- sqlfluff:templater:placeholder:param_style:pyformat
-- sqlfluff:disable:disable_progress_bar:deprecated
SELECT DISTINCT
    RESOURCE_ID,
    UPPER(AMAZON_RESOURCE_NAME) as AMAZON_RESOURCE_NAME,
    BA,
    ACCOUNT,
    CREATE_DATE,
    TYPE,
    FULL_RECORD,
    ROLE_TYPE,
    SF_LOAD_TIMESTAMP,
    CURRENT_TIMESTAMP() as LOAD_TIMESTAMP
FROM EIAM_DB.PHDP_CYBR_IAM.IDENTITY_REPORTS_IAM_RESOURCE_V3
WHERE TYPE = 'role'
    AND AMAZON_RESOURCE_NAME LIKE 'arn:aws:iam::%role/%'
    AND NOT REGEXP_LIKE(UPPER(FULL_RECORD), '.(DENY[-]?ALL|QUARANTINEPOLICY).')
    AND DATE(SF_LOAD_TIMESTAMP) = CURRENT_DATE
    AND ROLE_TYPE = 'MACHINE'
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RESOURCE_ID
    ORDER BY CREATE_DATE DESC
) = 1 