pipeline:
  name: pl_automated_monitoring_CTRL_1077224
  use_test_data_on_nonprod: false
  dq_strict_mode: false

stages:
  extract:
    threshold_df:
      connector: snowflake
      options:
        sql: "@text:sql/monitoring_thresholds.sql"
  
  ingress_validation:
    threshold_df:
      - type: count_check
        fatal: true
        envs:
          - qa
          - prod
        options:
          data_location: Snowflake
          threshold: 1
          table_name: ETIP_DB.PHDP_ETIP_CONTROLS_MONITORING.ETIP_CONTROLS_MONITORING_METRICS_DETAILS
      - type: schema_check
        fatal: true
        envs:
          - qa
          - prod
        options:
          data_location: Snowflake
          dataset_id: '3200d09e-69a8-49f1-9d61-fd164817364c'
          attribute_map: {}
    
    kms_key_rotation_df:
      - type: count_check
        fatal: true
        envs:
          - qa
          - prod
        options:
          data_location: API
          threshold: 1
          table_name: KMS_KEY_ROTATION
  
  load:
    kms_key_rotation_df:
      - connector: onestream
        options:
          table_name: etip_controls_monitoring_metrics
          business_application: BAENTERPRISETECHINSIGHTS
          file_type: AVRO
          avro_schema: "@json:avro_schema.json"

  prepare_test_data:
    threshold_df:
      - function: head
        options:
          n: 500000

  export_test_data:
    threshold_df: