-- sqlfluff:dialect:snowflake
-- sqlfluff:templater:placeholder:param_style:pyformat
-- Tier 0 query to detect certificates used after expiry without rotation
WITH EXPIRED_CERTS AS (
    SELECT 
        Certificate_ID,
        Certificate_ARN,
        NOT_VALID_BEFORE_UTC_TIMESTAMP,
        NOT_VALID_AFTER_UTC_TIMESTAMP as EXPIRY_DATE,
        LAST_USAGE_OBSERVATION_UTC_TIMESTAMP,
        -- Check for rotation
        LEAD(NOT_VALID_BEFORE_UTC_TIMESTAMP) OVER (
            PARTITION BY Certificate_ARN 
            ORDER BY NOT_VALID_BEFORE_UTC_TIMESTAMP
        ) as ROTATION_DATE
    FROM CYBR_DB.PHDP_CYBR.CERTIFICATE_CATALOG_CERTIFICATE_USAGE
    WHERE CERTIFICATE_ARN LIKE '%arn:aws:acm%'
    AND NOMINAL_ISSUER = 'Amazon'
    AND NOT_VALID_AFTER_UTC_TIMESTAMP < CURRENT_TIMESTAMP
    AND NOT_VALID_AFTER_UTC_TIMESTAMP >= DATEADD(day, -3, CURRENT_TIMESTAMP)
    AND LAST_USAGE_OBSERVATION_UTC_TIMESTAMP > NOT_VALID_AFTER_UTC_TIMESTAMP
)
SELECT
    COUNT(CASE WHEN ROTATION_DATE IS NULL OR ROTATION_DATE > EXPIRY_DATE THEN 1 END) as FAILURES_COUNT,
    CASE 
        WHEN COUNT(CASE WHEN ROTATION_DATE IS NULL OR ROTATION_DATE > EXPIRY_DATE THEN 1 END) > 0 
        THEN 'FAILED' ELSE 'PASSED'
    END as TEST_RESULT
FROM EXPIRED_CERTS