pipeline:
  name: pl_automated_monitoring_machine_iam
  use_test_data_on_nonprod: false
  dq_strict_mode: false

environments:
  prod:
    extract:
      thresholds_raw:
        connector: snowflake
        options:
          sql: "@text:sql/monitoring_thresholds.sql"
          params: $thresholds_raw_params
      iam_roles:
        connector: snowflake
        options:
          sql: "@text:sql/iam_roles.sql"
      evaluated_roles:
        connector: snowflake
        options:
          sql: "@text:sql/evaluated_roles.sql"
          params: $evaluated_roles_params
          multi_run: true
      sla_data:
        connector: snowflake
        options:
          sql: "@text:sql/sla_data.sql"
    load:
      monitoring_metrics:
        - connector: onestream
          options:
            table_name: etip_controls_monitoring_metrics
            file_type: AVRO
            avro_schema: "@json:avro_schema.json"
            business_application: BAENTERPRISETECHINSIGHTS

  local:
    extract:
      thresholds_raw:
        connector: snowflake
        options:
          sql: "@text:sql/monitoring_thresholds.sql"
          params: $thresholds_raw_params
      iam_roles:
        connector: snowflake
        options:
          sql: "@text:sql/iam_roles.sql"
      evaluated_roles:
        connector: snowflake
        options:
          sql: "@text:sql/evaluated_roles.sql"
          params: $evaluated_roles_params
          multi_run: true
      sla_data:
        connector: snowflake
        options:
          sql: "@text:sql/sla_data.sql"
    load:
      monitoring_metrics:
        - connector: onestream
          options:
            table_name: etip_controls_monitoring_metrics
            file_type: AVRO
            avro_schema: "@json:avro_schema.json"
            business_application: BAENTERPRISETECHINSIGHTS

ingress_validation:
  thresholds_raw:
    - type: schema_check
      fatal: false
      informational: true
      envs: [prod]
      options:
        required_columns:
          - monitoring_metric_id
          - control_id
          - monitoring_metric_tier
          - metric_name
          - metric_description
          - warning_threshold
          - alerting_threshold
    - type: count_check
      fatal: true
      envs: [prod]
      options:
        data_location: Snowflake
        threshold: 1
    - type: consistency_check
      fatal: false
      informational: true
      envs: [prod]
      options:
        check_type: "data_freshness"
        description: "Ingress data quality check"

  iam_roles:
    - type: schema_check
      fatal: false
      informational: true
      envs: [prod]
      options:
        required_columns:
          - RESOURCE_ID
          - AMAZON_RESOURCE_NAME
          - ROLE_TYPE
    - type: count_check
      fatal: true
      envs: [prod]
      options:
        data_location: Snowflake
        threshold: 1

  evaluated_roles:
    - type: schema_check
      fatal: false
      informational: true
      envs: [prod]
      options:
        required_columns:
          - resource_name
          - compliance_status
          - control_id
          - role_type
    - type: count_check
      fatal: false
      informational: true
      envs: [prod]
      options:
        data_location: Snowflake
        threshold: 1

egress_validation:
  monitoring_metrics:
    - type: schema_check
      fatal: false
      informational: true
      envs: [prod]
      options:
        required_columns:
          - control_monitoring_utc_timestamp
          - control_id
          - monitoring_metric_id
          - monitoring_metric_value
          - monitoring_metric_status
          - metric_value_numerator
          - metric_value_denominator
    - type: count_check
      fatal: false
      informational: true
      envs: [prod]
    - type: consistency_check
      fatal: false
      informational: true
      envs: [prod]
      options:
        description: "Egress data will not match ingress data due to API enrichment and multi-tier calculations"