pipeline:
  name: pl_automated_monitoring_machine_iam
  use_test_data_on_nonprod: false
  dq_strict_mode: false

stages:
  extract:
    thresholds_raw:
      connector: snowflake
      options:
        sql: "@text:sql/monitoring_thresholds.sql"
        params: $thresholds_raw_params
    iam_roles:
      connector: snowflake
      options:
        sql: "@text:sql/iam_roles.sql"
    evaluated_roles:
      connector: snowflake
      options:
        sql: "@text:sql/evaluated_roles.sql"
        params: $evaluated_roles_params  # Use the dynamic list of parameters (one for each cloud control ID)
        multi_run: true  # Execute the query multiple times with different parameters
    sla_data:
      connector: snowflake
      options:
        sql: "@text:sql/sla_data.sql"

  ingress_validation:
    thresholds_raw:
      - type: count_check
        fatal: true
        envs:
          - prod
        options:
          data_location: Snowflake
          threshold: 1
          table_name: ETIP_DB.PHDP_ETIP_CONTROLS_MONITORING.ETIP_CONTROLS_MONITORING_METRICS_DETAILS
    iam_roles:
      - type: count_check
        fatal: true
        envs:
          - prod
        options:
          data_location: Snowflake
          threshold: 1
          table_name: EIAM_DB.PHDP_CYBR_IAM.IDENTITY_REPORTS_IAM_RESOURCE_V3
    evaluated_roles:
      - type: count_check
        fatal: true
        envs:
          - prod
        options:
          data_location: Snowflake
          threshold: 1
          table_name: EIAM_DB.PHDP_CYBR_IAM.IDENTITY_REPORTS_CONTROLS_VIOLATIONS_STREAM_V2

  transform:
    monitoring_metrics:
      - function: custom/calculate_machine_iam_metrics
        options:
          thresholds_raw: $thresholds_raw
          iam_roles: $iam_roles
          evaluated_roles: $evaluated_roles
          sla_data: $sla_data

  load:
    monitoring_metrics:
      - connector: onestream
        options:
          table_name: etip_controls_monitoring_metrics
          file_type: AVRO
          avro_schema: "@json:avro_schema.json"
          business_application: BAENTERPRISETECHINSIGHTS

  prepare_test_data:
    thresholds_raw:
      - function: head
        options:
          n: 500000
    iam_roles:
      - function: head
        options:
          n: 500000
    evaluated_roles:
      - function: head
        options:
          n: 500000
    sla_data:
      - function: head
        options:
          n: 500000

  export_test_data:
    thresholds_raw:
    iam_roles:
    evaluated_roles:
    sla_data: