pipeline:
  name: pl_automated_monitoring_CTRL_1079134
  use_test_data_on_nonprod: false
  dq_strict_mode: false

stages:
  extract:
    threshold_df:
      connector: snowflake
      options:
        sql: "@text:sql/monitoring_thresholds.sql"
    macie_metrics_df:
      connector: snowflake
      options:
        sql: "@text:sql/macie_metrics.sql"
    macie_testing_df:
      connector: snowflake
      options:
        sql: "@text:sql/macie_testing.sql"
    historical_stats_df:
      connector: snowflake
      options:
        sql: "@text:sql/historical_stats.sql"
  
  ingress_validation:
    threshold_df:
      - type: count_check
        fatal: true
        envs:
          - qa
          - prod
        options:
          data_location: Snowflake
          threshold: 1
          table_name: ETIP_DB.PHDP_ETIP_CONTROLS_MONITORING.ETIP_CONTROLS_MONITORING_METRICS_DETAILS
      - type: schema_check
        fatal: true
        envs:
          - qa
          - prod
        options:
          data_location: Snowflake
          dataset_id: '3200d09e-69a8-49f1-9d61-fd164817364c'
          attribute_map: {}
    
    macie_metrics_df:
      - type: count_check
        fatal: true
        envs:
          - qa
          - prod
        options:
          data_location: Snowflake
          threshold: 1
          table_name: CYBR_DB.PHDP_CYBR.MACIE_METRICS_V3
    
    macie_testing_df:
      - type: count_check
        fatal: false
        envs:
          - qa
          - prod
        options:
          data_location: Snowflake
          threshold: 1
          table_name: CYBR_DB.PHDP_CYBR.MACIE_CONTROLS_TESTING
  
  transform:
    macie_monitoring_df:
      - function: custom/transform_macie_data
        options:
          threshold_df: $threshold_df
          macie_metrics_df: $macie_metrics_df
          macie_testing_df: $macie_testing_df
          historical_stats_df: $historical_stats_df

  load:
    macie_monitoring_df:
      - connector: onestream
        options:
          table_name: etip_controls_monitoring_metrics
          business_application: BAENTERPRISETECHINSIGHTS
          file_type: AVRO
          avro_schema: "@json:avro_schema.json"

  prepare_test_data:
    threshold_df:
      - function: head
        options:
          n: 500000
    macie_metrics_df:
      - function: head
        options:
          n: 500000
    macie_testing_df:
      - function: head
        options:
          n: 500000
    historical_stats_df:
      - function: head
        options:
          n: 500000

  export_test_data:
    threshold_df:
    macie_metrics_df:
    macie_testing_df:
    historical_stats_df: