pipeline:
  name: pl_automated_monitoring_CTRL_1106680
  use_test_data_on_nonprod: false
  dq_strict_mode: false
  stages:
    # REQUIRED: Comprehensive Data Quality Validation
    ingress_validation:
      thresholds_raw:
        - type: schema_check
          fatal: false
          informational: true
          envs: [local, prod]
          options:
            required_columns:
              - monitoring_metric_id
              - control_id
              - monitoring_metric_tier
              - metric_name
              - metric_description
              - warning_threshold
              - alerting_threshold
              - control_executor
        - type: count_check
          fatal: true
          envs: [local, prod]
          options:
            data_location: Snowflake
            threshold: 1
        - type: consistency_check
          fatal: false
          informational: true
          envs: [local, prod]
          options:
            check_type: "data_freshness"
            description: "Ingress data quality check"
    
      in_scope_roles:
        - type: schema_check
          fatal: false
          informational: true
          envs: [local, prod]
          options:
            required_columns:
              - AMAZON_RESOURCE_NAME
        - type: count_check
          fatal: true
          envs: [local, prod]
          options:
            data_location: Snowflake
            threshold: 1
        - type: consistency_check
          fatal: false
          informational: true
          envs: [local, prod]
          options:
            description: "In-scope roles data quality check"
    
      evaluated_roles:
        - type: schema_check
          fatal: false
          informational: true
          envs: [local, prod]
          options:
            required_columns:
              - RESOURCE_NAME
        - type: count_check
          fatal: false
          informational: true
          envs: [local, prod]
          options:
            data_location: Snowflake
            threshold: 1
        - type: consistency_check
          fatal: false
          informational: true
          envs: [local, prod]
          options:
            description: "Evaluated roles data quality check"
    
    egress_validation:
      monitoring_metrics:
        - type: schema_check
          fatal: false
          informational: true
          envs: [local, prod]
          options:
            required_columns:
              - control_monitoring_utc_timestamp
              - control_id
              - monitoring_metric_id
              - monitoring_metric_value
              - monitoring_metric_status
              - metric_value_numerator
              - metric_value_denominator
        - type: count_check
          fatal: false
          informational: true
          envs: [local, prod]
        - type: consistency_check
          fatal: false
          informational: true
          envs: [local, prod]
          options:
            description: "Egress data will not match ingress data due to metric calculations"

environments:
  prod:
    extract:
      thresholds_raw:
        connector: snowflake
        options:
          sql: "@text:sql/monitoring_thresholds.sql"
      in_scope_roles:
        connector: snowflake
        options:
          sql: "@text:sql/in_scope_roles.sql"
      evaluated_roles:
        connector: snowflake
        options:
          sql: "@text:sql/evaluated_roles.sql"
    load:
      monitoring_metrics:
        - connector: onestream
          options:
            table_name: etip_controls_monitoring_metrics
            file_type: AVRO
            avro_schema: "@json:avro_schema.json"
            business_application: BAENTERPRISETECHINSIGHTS

  local:
    extract:
      thresholds_raw:
        connector: snowflake
        options:
          sql: "@text:sql/monitoring_thresholds.sql"
      in_scope_roles:
        connector: snowflake
        options:
          sql: "@text:sql/in_scope_roles.sql"
      evaluated_roles:
        connector: snowflake
        options:
          sql: "@text:sql/evaluated_roles.sql"
    load:
      monitoring_metrics:
        - connector: onestream
          options:
            table_name: etip_controls_monitoring_metrics
            file_type: AVRO
            avro_schema: "@json:avro_schema.json"
            business_application: BAENTERPRISETECHINSIGHTS